extends:
  - esnext

env:
  es6: true
  browser: true
  node: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    modules: true

plugins: ['html', 'markdown']

overrides: [{
    files: ["**/*.md"],
    rules: {
        no-undef: "off",
        no-unused-vars: "off",
        import/no-unresolved: "off"
    }
}]