name: PR CI

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  shared-ci:
    uses: kurkle/configs/.github/workflows/shared-ci.yml@v1
    with:
      fetch-depth: 1
      run-audit-signatures: false
      coverage-paths: |
        coverage/chrome/lcov.info
        coverage/firefox/lcov.info
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
